
- name: Instalando jenkins
  hosts: automation.dexter.com.br
  tasks:
    - name: Add repository
      yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: http://pkg.jenkins.io/redhat-stable 
        gpgcheck: yes

    - name: Add GPG key
      rpm_key:
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present

    - name: Install packages
      package:
        name:
          - java-1.8.0
          - jenkins
        state: latest

